return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "hyprlang",
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "c_sharp",
      "bicep",
      "razor",
      "yaml",
      "caddy",
      "bash",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "markdown_inline",
      "php",
      "python",
      "rust",
      "sql",
      "styled",
      "tsx",
      "typescript",
      "zig",
      "regex",
      "javascript",
    },
  },
}
